[package]
name = "telecaster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inventory = "0.2"
once_cell = "1.12"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
